### ISSUE TITLE
1.18 version crashes the game on startup

### ISSUE THREAD

**Issue by pesegolsson** [hamusuke0323/FlyCommandMod-Fabric#1]
tried the 1.18 version and it crashes the game on startup. i get:
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'flycommand'!
Exit Code: -1

crashlog: (some of it is in swedish though, but i gues the important parts are readable to you)
[crash-2021-12-08_23.17.09-client.txt](https://github.com/hamusuke0323/FlyCommandMod-Fabric/files/7679420/crash-2021-12-08_23.17.09-client.txt)

i have tried it with only the flycommand and latest(0.44.0) fabric api with same result. hope you can fix it!

**Comment by hamusuke0323** [comment]
Thank you for reporting. I'm fixing it.

**Comment by hamusuke0323** [comment]
done. I fixed this bug.

**Comment by pesegolsson** [comment]
thank you, seam to be working fine now!
