### ISSUE TITLE
disableDamage has no effect

### ISSUE THREAD

**Issue by ghost** [hamusuke0323/FlyCommandMod-Fabric#3]
Hey,
setting `/fly @playername disableDamage false` has no effect. The player wont take any fall damage whilst fly ist set to enabled. 
I am on the latest 1.19 version. The behaviour was the same for a 1.18 version I tested. Does this feature also not work when playing on a server or am I missing something?

**Comment by hamusuke0323** [comment]
The player doesnt take fall damage while the player is flyable.
